package com.verschraenkt.ci.storage.db.tables

import com.verschraenkt.ci.storage.db.PostgresProfile.MyAPI.{ circeJsonTypeMapper, simpleStrListTypeMapper }
import com.verschraenkt.ci.storage.db.PostgresProfile.api.*
import com.verschraenkt.ci.storage.db.codecs.Enums.{ Architecture, ExecutorStatus, Platform }
import com.verschraenkt.ci.storage.db.codecs.ColumnTypes.given
import io.circe.Json

import java.time.Instant
import java.util.UUID

/** Models a registered executor row in {@code executors} , including capacity, runtime metadata, scheduling
  * labels and lifecycle timestamps.
  *
  * @param executorId
  *   Primary key/UUID generated by the controller
  * @param name
  *   Human-friendly executor name
  * @param hostname
  *   Hostname reported by the agent
  * @param platform
  *   Operating system / distribution classification
  * @param architecture
  *   CPU architecture supported by the executor
  * @param cpuMillis
  *   Total CPU capacity expressed in milli-cores
  * @param memoryMibs
  *   Available memory capacity in MiB
  * @param gpuCount
  *   Number of GPU devices available
  * @param diskMibs
  *   Disk capacity advertised in MiB
  * @param labels
  *   Arbitrary label list for scheduling/affinity
  * @param status
  *   Current executor status (online, draining, offline, etc.)
  * @param registeredAt
  *   When the executor first registered
  * @param lastHeartbeat
  *   Timestamp of the latest heartbeat message
  * @param lastJobAt
  *   When the executor last ran any job
  * @param tokenHash
  *   Hash of the registration/authentication token
  * @param version
  *   Optional agent version string
  * @param metadata
  *   JSON payload with executor-specific metadata
  * @param deletedAt
  *   Soft-delete timestamp when executor is decommissioned
  */
case class ExecutorRow(
    executorId: Option[UUID],
    name: String,
    hostname: Option[String],
    platform: Platform,
    architecture: Architecture,
    cpuMillis: Int,
    memoryMibs: Int,
    gpuCount: Int,
    diskMibs: Int,
    labels: List[String],
    status: ExecutorStatus,
    registeredAt: Instant,
    lastHeartbeat: Instant,
    lastJobAt: Option[Instant],
    tokenHash: String,
    version: Option[String],
    metadata: Json,
    deletedAt: Option[Instant]
)

class ExecutorTable(tag: Tag) extends Table[ExecutorRow](tag, "executors"):
  def executorId    = column[UUID]("executor_id", O.PrimaryKey, O.AutoInc)
  def name          = column[String]("name")
  def hostname      = column[Option[String]]("hostname")
  def platform      = column[Platform]("platform")
  def architecture  = column[Architecture]("architectures")
  def cpuMillis     = column[Int]("cpu_milli")
  def memoryMibs    = column[Int]("memory_mib")
  def gpuCount      = column[Int]("gpu")
  def diskMibs      = column[Int]("disk_mib")
  def labels        = column[List[String]]("labels")
  def status        = column[ExecutorStatus]("status")
  def registeredAt  = column[Instant]("registered_at")
  def lastHeartbeat = column[Instant]("last_heartbeat")
  def lastJobAt     = column[Option[Instant]]("last_job_at")
  def tokenHash     = column[String]("token_hash")
  def version       = column[Option[String]]("version")
  def metadata      = column[Json]("metadata")
  def deletedAt     = column[Option[Instant]]("deleted_at")

  def * = (
    executorId.?,
    name,
    hostname,
    platform,
    architecture,
    cpuMillis,
    memoryMibs,
    gpuCount,
    diskMibs,
    labels,
    status,
    registeredAt,
    lastHeartbeat,
    lastJobAt,
    tokenHash,
    version,
    metadata,
    deletedAt
  ) <> ((ExecutorRow.apply).tupled, ExecutorRow.unapply)
